services:
  hephaestus-bot:
    image: ghcr.io/kadams365/hephaestus:latest
    container_name: hephaestus-bot
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      CLIENT_ID: ${CLIENT_ID}
      GUILD_ID: ${GUILD_ID}
      ALERT_CHANNEL_ID: ${ALERT_CHANNEL_ID}
      DATA_DIR: ${DATA_DIR}
    volumes:
      - ./data:/usr/src/app/data
    restart: unless-stopped
